### ISSUE TITLE
Aspect-ratio

### ISSUE THREAD

**Issue by sobhanjahangir** [refinedguides/custom-datepicker#1]
Not a big problem, but one that I came across. The aspect-ration needs to be 2 and not 1. Then you will cover the whole numbers in the calendar and not only half of the box.

.dates button {
  color: slategray;
  aspect-ratio: 2;

**Comment by refinedguides** [comment]
Hi, sorry for the late reply. Could it be the font size is bigger? The aspect ratio is mainly to make sure the button is square.
